spring:
  application:
    name: coffee

  profiles:
    active: dev
    group:
      "dev": "dev, secrets, jwt, oauth"
      "local" : "local, secrets, jwt, oauth"

server:
  port: 8080
  forward-headers-strategy: native

file:
  dir: src/main/resources/images/
